import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {handleRespond,validResponse} from '../functions/api/respond.js';
const now=Date.parse('2026-10-05T09:00:00Z'), origin='https://invitation.example';
const payload={accepted:true,date:'2026-10-23',time:'16:30',senderName:'Максим',requestId:'12345678-1234-4234-8234-123456789abc',turnstileToken:'test-challenge'};
function setup(t){
 const db=new DatabaseSync(':memory:');db.exec(readFileSync('migrations/0001_state.sql','utf8'));t.after(()=>db.close());
 const env={SENDER_NAME:'Максим',TELEGRAM_BOT_TOKEN:'test-only',TELEGRAM_CHAT_ID:'123',TURNSTILE_SECRET_KEY:'test-only',DB:{prepare(sql){return {bind(...args){return {async first(){return db.prepare(sql).get(...args)||null;},async run(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}};}};}};}}};
 const context=(body=payload,overrides={})=>{const init={method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1'},body:JSON.stringify(body),...overrides};if(init.method==='GET')delete init.body;return {request:new Request(origin+'/api/respond',init),env};};
 let sends=0;
 const send=async(url,options)=>{if(url.includes('siteverify'))return Response.json({success:true,hostname:'invitation.example',action:'date_response'});sends++;const message=JSON.parse(options.body);assert.equal(message.chat_id,'123');assert.match(message.text,/23 октября 2026.*\nВремя: 16:30 \(Europe\/Kyiv\)/);return Response.json({ok:true,result:{message_id:1}});};
 return {context,send,db,get sends(){return sends;}};
}
test('486 valid choices; strict schema',()=>{for(let d=5;d<=31;d++)for(let i=0;i<18;i++)assert(validResponse({...payload,date:`2026-10-${String(d).padStart(2,'0')}`,time:`${10+Math.floor(i/2)}:${i%2?'30':'00'}`},'Максим'));for(const date of ['2026-10-04','2026-10-32','2026-11-01',null])assert(!validResponse({...payload,date},'Максим'));for(const time of ['09:30','18:31','19:00','10:15',null])assert(!validResponse({...payload,time},'Максим'));for(const extra of [{chat_id:'999'},{text:'hello'},{accepted:false},{senderName:'Someone'},{requestId:'bad'},{turnstileToken:''}])assert(!validResponse({...payload,...extra},'Максим'));});
test('concurrent claims send once; cached success; conflicting payload',async t=>{const f=setup(t);const results=await Promise.all([handleRespond(f.context(),f.send,now),handleRespond(f.context(),f.send,now)]);assert(results.some(r=>r.status===200));assert.equal(f.sends,1);assert.equal((await handleRespond(f.context(),f.send,now)).status,200);assert.equal(f.sends,1);assert.equal((await handleRespond(f.context({...payload,time:'17:00'}),f.send,now)).status,409);});
test('bounds, origin, schema, missing bindings and rate limit fail closed',async t=>{const f=setup(t);for(const [ctx,status]of [[f.context(payload,{method:'GET'}),405],[f.context({...payload,chat_id:'999'}),400],[f.context(payload,{body:'x'.repeat(4097)}),413],[f.context(payload,{headers:{Origin:'https://other.example','Content-Type':'application/json'}}),403]])assert.equal((await handleRespond(ctx,f.send,now)).status,status);const ctx=f.context();ctx.env={};assert.equal((await handleRespond(ctx,f.send,now)).status,503);for(let i=0;i<6;i++)assert.equal((await handleRespond(f.context(),async()=>Response.json({success:false}),now)).status,i<5?403:429);assert.equal(f.sends,0);});
test('past dates and expiry use Kyiv midnight',async t=>{const f=setup(t);assert.equal((await handleRespond(f.context({...payload,date:'2026-10-05'}),f.send,Date.parse('2026-10-05T21:00:00Z'))).status,400);assert.equal((await handleRespond(f.context(),f.send,Date.parse('2026-10-31T22:00:00Z'))).status,410);assert.equal(f.sends,0);});
test('ambiguous outcome never resent; rejected message can retry; no secret responses',async t=>{for(const uncertain of [true,false]){const f=setup(t);const failure=async(url,options)=>{if(url.includes('siteverify'))return f.send(url,options);if(uncertain)throw new Error('private details');return Response.json({ok:false,description:'private details'});};const result=await handleRespond(f.context(),failure,now);assert.equal(result.status,uncertain?409:502);assert(!(await result.text()).includes('private'));assert.equal((await handleRespond(f.context(),f.send,now)).status,uncertain?409:200);assert.equal(f.sends,uncertain?0:1);}});
test('invalid Turnstile hostname/action never reaches Telegram',async t=>{const f=setup(t);for(const answer of [{success:true,hostname:'evil.example',action:'date_response'},{success:true,hostname:'invitation.example',action:'other'}])assert.equal((await handleRespond(f.context(),async()=>Response.json(answer),now)).status,403);assert.equal(f.sends,0);});
